README.md, examples/gcd.py, examples/hello.py, examples/linking.py, examples/memory.py, examples/multi.py, tests/test_func.py, tests/test_instance.py, wasmtime/_func.py, wasmtime/_instance.py
Remove `Instance.get_export` as well as `Caller.get_export`. The former
is replaced with string indexing on `Instance.exports` and the latter is
replaced with string indexing on `Caller`
Closes #4
=> Fold `get_export` into `exports`

.github/workflows/main.yml, download-wasmtime.py
This updates the built wheels to include MinGW ones (apparently normal
Windows ones don't automatically work here) as well as AArch64 ones.
I've done my best to figure out what the `--plat-name` argument should
be, but we can alwyas tweak it over time!
Closes #10
Closes #12
=> Publish MinGW and AArch64 wheels

setup.py, wasmtime/_config.py, wasmtime/_engine.py, wasmtime/_extern.py, wasmtime/_func.py, wasmtime/_globals.py, wasmtime/_instance.py, wasmtime/_linker.py, wasmtime/_memory.py, wasmtime/_module.py, wasmtime/_store.py, wasmtime/_table.py, wasmtime/_trap.py, wasmtime/_types.py, wasmtime/_value.py, wasmtime/_wasi.py
This fixes `python_requires` in `setup.py` to be `>= 3.5` since that's what's tested and supported. I don't know how this fix affects things, but it might cause problems when someone with Python 2 tries to install wasmtime-py and it might cause problems with wheel names.
In Python 3, classes don't need to subclass object--all classes are new-style now. This is cosmetic and doesn't change the behavior of anything.
=> Remove Python 2-isms

wasmtime/_value.py
The use of the `long` (with no `# noqa`) was failing the `flake8` CI test.
=> Inline is_integer(), which is not needed as we require Python 3

setup.py
Also. Python 3.6 gave us [f-strings](https://www.python.org/downloads/release/python-360/)!
=> Require Python 3.6 (not 3.5), as this is the lowest version the CI tests

.github/workflows/main.yml, .gitignore, MANIFEST.in, download-wasmtime.py, wasmtime/_ffi.py
* Produce all wheels on one builder
* Produce an "any" wheel as a catch-all platform
* Rename where libraries are located - allows the "catch-all wheel" to have multiple precompiled libraries
* Fixup CI in a number of ways
=> Update how wheels are produced

.github/workflows/main.yml, .gitignore, bindgen.py, download-wasmtime.py, pytest.ini, setup.py, wasmtime/_bindings.py, wasmtime/_config.py, wasmtime/_engine.py, wasmtime/_error.py, wasmtime/_extern.py, wasmtime/_ffi.py, wasmtime/_func.py, wasmtime/_globals.py, wasmtime/_instance.py, wasmtime/_linker.py, wasmtime/_memory.py, wasmtime/_module.py, wasmtime/_store.py, wasmtime/_table.py, wasmtime/_trap.py, wasmtime/_types.py, wasmtime/_wasi.py, wasmtime/_wat2wasm.py
This commit migrates this binding of Wasmtime to auto-generate `ctypes`
definitions for all exported functions and types from wasmtime. The goal
of this is to automate binding generation and avoid having to hand-write
all imported types/functions. Currently all our functions stylistically
specify their return types (some for correctness), and this makes it so
they're procedurally generated and additionally specify argument types.
This should enable us to get better type checking with `ctypes` itself
as well as enable type annotations in this library since all imported
functions are procedurally generated and typed accordingly.
=> Auto-generate FFI bindings with `ctypes`

tests/test_trap.py, wasmtime/__init__.py, wasmtime/_bindings.py, wasmtime/_trap.py
* Add an `ExitTrap` subclass of `Trap`
* Return an appropriate trap from `Trap.__from_ptr__`
* Attach the exit code via a `code` field
Closes #30
=> Bind `wasmtime_trap_exit_status`

wasmtime/_config.py, wasmtime/_engine.py, wasmtime/_func.py, wasmtime/_globals.py, wasmtime/_instance.py, wasmtime/_linker.py, wasmtime/_memory.py, wasmtime/_module.py, wasmtime/_store.py, wasmtime/_table.py, wasmtime/_trap.py, wasmtime/_types.py, wasmtime/_value.py, wasmtime/_wasi.py
Stylistically we shouldn't use double under for non-builtin fields.
=> Rename `Val.__raw__` to `Val._raw`

CONTRIBUTING.md, README.md
Also update the set up and testing instructions.
=> Split contribution instructions out to CONTRIBUTING.md

tests/test_refs.py, wasmtime/_bindings.py, wasmtime/_store.py
This allows running an explicit GC pass if desired. Additionally add
some tests to make sure destructors are called correctly.
=> Add bindings for `Store.gc`

examples/loader.py, examples/loader_load_wasi.wat, wasmtime/loader.py
Hi @alexcrichton.
I found that `wasmtime.loader` can't import the module importing `wasi_snapshot_preview1`
```python
import wasmtime.loader
import hello_wasi # module using wasi_snapshot_preview1
```
```bash
$ python load_test.py
...
load_test.py:2: in <module>
import hello_wasi
wasmtime/loader.py:71: in exec_module
imported_module = importlib.import_module(module_name)
../.pyenv/versions/3.8.2/lib/python3.8/importlib/__init__.py:127: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
E   ModuleNotFoundError: No module named 'wasi_snapshot_preview1'
```
Currently, the loader can import any python modules, but loader must skip predefined modules in this library.
How about this fix?
=> Fix wasmtime.loader to import module using wasi_snapshot_preview1

README.md
When I first tried out the example in the README.md, I hit this `TypeError` exception: 
```
Traceback (most recent call last):
File "ex.py", line 4, in <module>
module = Module(store, """
File "repos/wasmtime-py/wasmtime/_module.py", line 21, in __init__
raise TypeError("expected an Engine")
TypeError: expected an Engine
```
The `Module` class used to take a `Store` but it has changed to take a `Engine` instead, so I've adapted accordingly. If I run this script (copying and pasting from the README.md example) I get the expected outcome: 
```
❯ python script.py
Hello from Python!
```
Awesome project by the way.
=> Fixed Python hello example on README.md

tests/test_instance.py, tests/test_module.py, tests/test_module_linking.py, tests/test_trap.py, wasmtime/__init__.py, wasmtime/_bindings.py, wasmtime/_config.py, wasmtime/_exportable.py, wasmtime/_extern.py, wasmtime/_instance.py, wasmtime/_linker.py, wasmtime/_module.py, wasmtime/_types.py
This updates the Python extension with the API support added in
bytecodealliance/wasmtime#2472. Most of the changes here were pretty
straightforward!
=> Add support for the module linking proposal

bindgen.py, wasmtime/_bindings.py, wasmtime/_func.py, wasmtime/_instance.py
Updates this binding for bytecodealliance/wasmtime#2579
=> Update for recent C API changes

tests/test_linker.py, wasmtime/_linker.py
These are wasmtime-specific and forgot to bind them before! Additionally
add some documentation to the `Linker`-related methods.
=> Bind some more linker APIs

wasmtime/loader.py
This is showing off how I'm not exactly a Python expert, but the
previous iteration didn't work because lambda closure captures didn't
work as I expected!
Closes #65
=> Fix `wasmtime.loader` with multiple functions

tests/test_store.py, wasmtime/_bindings.py, wasmtime/_config.py, wasmtime/_engine.py, wasmtime/_store.py
Handles the changes made in bytecodealliance/wasmtime#3925
=> Remove InterruptHandle, bind epochs

examples/loader.py, examples/loader_load_wasi.wat
The loader imports the `loader_load_wasi.wat` file which imports `random_get` from WASI. This PR extends the example to export a function which we can call in the host environment that leverages the `random_get` function.
=> Added exported function to the loader wasi wat

.github/workflows/main.yml, download-wasmtime.py, setup.py, wasmtime/_ffi.py
This PR adds support for macOS arm64 platforms. Changes are as follows:
1. Handle platform.machine() == arm64 for macOS.
Upstream wasmtime releases use aarch64-macos as part of the file name. On aarch64 macOS, platform.machine() returns 'arm64' instead. With this change, download-wasmtime.py correctly downloads aarch64-macos binaries and _ffi.py correctly loads them.
2. Build wheels for macOS arm64 in CI. This should close #79.
I ran tests on macOS-arm64 with python 3.8.9 using `pytest`, and two failures were reported:
```
FAILED tests/test_trap.py::TestTrap::test_frames - AssertionError: 1 != 3
FAILED tests/test_trap.py::TestTrap::test_frames_no_module - AssertionError: 0 != 1
```
(The PR is "draft" because of this failure.)
I have also tested a relatively simple project (`astyle` code …
=> add support for macOS arm64, build wheels

bindgen.py, wasmtime/_bindings.py, wasmtime/_error.py, wasmtime/_extern.py, wasmtime/_ffi.py, wasmtime/_func.py, wasmtime/_instance.py, wasmtime/_linker.py, wasmtime/_memory.py, wasmtime/_module.py, wasmtime/_store.py, wasmtime/_trap.py, wasmtime/_types.py, wasmtime/_value.py, wasmtime/_wasi.py
It appears that `ctypes.pointer` no longer works and poking at PRs it appears to be replace-able with `ctypes._Pointer`.
=> Update mypy type annotations

CONTRIBUTING.md
I was looking at wasmtime-py's `CONTRIBUTING.md` for inspiration for wasmitme-rb and found 2 dead links for markdown files:
- `CODE_OF_CONDUCT.md`
- `ORG_CODE_OF_CONDUCT.md`
I'm fixing these by linking to wasmtime's.
There's another dead link for test coverage (https://bytecodealliance.github.io/wasmtime-py/coverage/), but wasn't sure how to fix that one.
=> Fix 404s in CONTRIBUTING.md

wasmtime/_linker.py
Type checker complains the type is partially unknown when the type isn't fully defined. This will fix it.
=> fix: typing for Callable in linker.define_func

tests/test_global.py, wasmtime/_globals.py
Implements the change suggested in #141.
=> Fix Global.value to use None check instead of truthy check

.github/workflows/main.yml
Do not fail pull requests that do not upgrade the version of wasmtime-py as discussed at:
https://github.com/pypa/gh-action-pypi-publish#tolerating-release-package-file-duplicates
=> Do not fail GitHub Actions on push to test PyPI

rust/bindgen/src/bindgen.rs, tests/codegen/test_external_types.py
This commit adds the qualified module name to assignement that are imported from a separate modules.
The motivation for this is that currently this will cause a NameError. For example, if we have types defined in a Python module named demo_types, the variant assignement generated by bindgen will be:
```python
from ..imports import demo_types
variant = RuntimeValueString(list)
```
Which will generate the following error:
```console
Traceback (most recent call last):
File "/wasmtime-py/demo-module/demo.py", line 12, in <module>
main()
File "wasmtime-py/demo-module/demo.py", line 8, in main
ret = wit.something(store)
^^^^^^^^^^^^^^^^^^^^
File "wasmtime-py/demo-module/dist/exports/wit.py", line 27,
in something
variant = RuntimeValueString(list)
^^^^^^^^^^^^^^^^^^
NameError: name …
```
=> Add module name to missing assignment

rust/bindgen/src/bindgen.rs, tests/codegen/test_keywords.py
This avoids runtime syntax errors by adding an underscore suffix to identifiers which would otherwise match Python keywords.
Fixes #150
=> escape keywords in generated bindings

setup.py
This is a very minor change, just making the code more idiomatic
=> MAINT Use `subprocess.run` rather than `os.popen`

tests/test_refs.py, wasmtime/_value.py
Before this PR the added test fails with:
```
TypeError: don't know how to convert 5 to anyref
```
=> FIX Make it possible to convert a Python int/float to externref

tests/test_wasi.py, wasmtime/_wasi.py
Generally Python APIs that take paths accept the path as a `str`, `bytes` or `PathLike`. This makes a few wasmtime-py apis follow this convention.
=> ENH Support PathLike in `config.stdxxx_file = path`

tests/test_instance.py, tests/test_linker.py, tests/test_table.py, tests/test_trap.py, wasmtime/_instance.py, wasmtime/loader.py
This is a breaking API change. I expected `InstanceExports` to be a subclass of `Mapping`. This PR includes a few changes:
1. `__iter__` should return an iterator over the **keys** of the map, not over the values.
2. we are expected to implement `__getitem__`, a `.get` method is derived automatically.
3. It's a bit unexpected that you can index both by the keys and by the index. It makes it hard to satisfy mypy, and it makes it hard to satisfy the invariants of `Mapping` (for instance, that `val in map` iff `val in list(map)`). I think it's reasonably natural to expose directly a tuple, typed as a `Sequence`, with the exports if we want to index them. I called this field `by_index`. For good measure, I made it a getter so that attempts to assign to it fail.
=> API Make InstanceExports into a Mapping

.github/actions/setup/action.yml, .github/workflows/main.yml, README.md, setup.py, wasmtime/_instance.py, wasmtime/_wasi.py
Also add 3.8 to CI explicitly 
cc https://github.com/bytecodealliance/wasmtime-py/issues/189
=> Raise minimum Python version to 3.8

tests/test_config.py, tests/test_engine.py, tests/test_store.py, wasmtime/__init__.py, wasmtime/_config.py, wasmtime/_engine.py, wasmtime/_error.py, wasmtime/_extern.py, wasmtime/_func.py, wasmtime/_globals.py, wasmtime/_instance.py, wasmtime/_linker.py, wasmtime/_managed.py, wasmtime/_memory.py, wasmtime/_module.py, wasmtime/_store.py, wasmtime/_table.py, wasmtime/_trap.py, wasmtime/_types.py, wasmtime/_wasi.py
This commit adds a suite of methods to most of the types in this package to enable explicit destruction of resources as necessary. Specifically most classes which own a pointer internally now sport some new methods:
* `__enter__` and `__exit__` enable using the objects in `with` blocks.
* `close` enables explicitly deallocating the object.
All objects internally now validate that they have not been closed before operating, raising a `ValueError` if a closed object is operated on.
=> Enable explicit destruction of all resources

tests/test_config.py, wasmtime/_config.py
This PR adds support for configuring tail calls (Closes https://github.com/bytecodealliance/wasmtime-py/issues/204),
it depends on the change to the C api here: https://github.com/bytecodealliance/wasmtime/pull/7811,
without the change, the CI fails as expected with: `[...] _libwasmtime.so: undefined symbol: wasmtime_config_wasm_tail_call_set.`
=> support configuring tail calls

wasmtime/loader.py
Python does have cwd on `sys.path` by default:
>>> import sys; sys.path[0]
''
However, having cwd on `sys.path` is potentially a security issue (see [safepath]) and the custom loader should absolutely not add it itself since this circumvents `PYTHONSAFEPATH=1`, `-P` and other knobs that Python provides to fixes the default-unsafe behavior.
Before this commit, any application using `wasmtime.loader` can be subverted if it is ran in a cwd controlled by an attacker so that it runs a completely different Wasm module. Since WASI is enabled by default this means arbitrary code execution, even with `PYTHONSAFEPATH` set.
[safepath]: https://docs.python.org/3/using/cmdline.html#cmdoption-P
=> loader: do not prepend cwd to path as it is a security issue

wasmtime/_types.py, wasmtime/loader.py
Depends on https://github.com/bytecodealliance/wasmtime-py/pull/221.
This is an incremental but substantial improvement, to the point where I'd say I consider this implementation correct, or very close to correct, according to my understanding of the importlib hooks involved.
It is however still not thread-safe, I will likely address that after adding component support.
=> loader: assorted fixes

examples/loader_component.py, examples/loader_component_add.wat, rust/src/bindgen.rs, setup.py, wasmtime/loader.py
Fixes #220.
Closes #219.
Depends on #221.
Depends on #222.
Works like this:
```
$ ls
wavedrom.wasm    ...
$ python -c 'import wasmtime.loader, json, wavedrom; store = wasmtime.Store(); print(wavedrom.Root(store).render_json(store, json.dumps({"signal": [{ "name": "clk", "wave": "p..." }, { "name": "data", "wave": "0110" }]})))'
<svg xmlns="http://www.w3.org/2000/svg" ....
```
=> loader: add support for components

ci/download-wasmtime.py, wasmtime/__init__.py, wasmtime/_bindings.py, wasmtime/_func.py, wasmtime/_globals.py, wasmtime/_table.py, wasmtime/_value.py
Handle some updates related to externref and change how `Val` works by making it no longer store `wasmtime_val_t` but instead store the raw value itself which is converted to `wasmtime_val_t` on-the-fly.
=> Update to latest bindings

.github/actions/setup/action.yml, .github/workflows/main.yml, ci/download-wasmtime.py
Use binaries from bytecodealliance/wasmtime#8668 to add a musl wheel.
cc #237
=> Add a wheel for `musllinux_1_2_x86_64`

ci/cbindgen.py, ci/download-wasmtime.py, rust/Cargo.lock, rust/Cargo.toml, rust/src/bindgen.rs, tests/test_wasi.py, wasmtime/__init__.py, wasmtime/_bindings.py, wasmtime/_table.py, wasmtime/_types.py, wasmtime/_wasi.py
Closes #251 
As discussed in there:
* Updates to latest dev wasmtime and latest wasmtime release (26) for rust bindgen code
* Translates enums in c headers into python-accessible values.
* Wraps new preopen file/directory permissions into a public python API.
* A few other minor changes to accommodate dev changes (32 -> 64 bits, a new "shared" flag)
There is more we could do using the exposed enums (in existing bindings where we have numbers now) and exposing new APIs but thought we'd land this first.
=> Update to latest wasmtime dev

setup.py, tests/test_wasi.py, wasmtime/_wasi.py
Keeps this the same way it was before in terms of defaults, but new
behavior can be opted-in to as well.
Closes #259
=>  Add defaults for preopen_dir arguments 

README.md
wasm-tools component embed -w demo demo.wit demo.wat -o demo.wasm error: expected '{', found keyword `world`
--> demo.wit:3:1
|
3 | world demo {
wasm-tools --version
wasm-tools 1.222.0
=> Fix WIT declaration in the component example

.github/workflows/main.yml, CONTRIBUTING.md, README.md, ci/cbindgen.py, ci/download-wasmtime.py, setup.py, tests/bindgen/__init__.py, wasmtime/_ffi.py, wasmtime/_func.py
This is for issue #247 . Putting up for early review, but some testing on other platforms and a couple questions remain.
=> Support Windows on ARM64
