bytecodealliance/wasmtime-py

examples/multi.py
tests/test_table.py
wasmtime/__init__.py
wasmtime/_extern.py
wasmtime/_table.py

Binding support added in https://github.com/bytecodealliance/wasmtime/pull/1654

Bind new wasmtime functions to get/set/make tables

---

README.md

I hope this helps! I was confused by a few things, and thought this might help others.
There are plenty of other things I'd like to see improved, but this hits the main things.

Make the README a little more clear and neat, and add a link to flake8

---

examples/gcd.py
examples/hello.py
examples/memory.py
examples/multi.py
tests/test_func.py
tests/test_instance.py
tests/test_linker.py
tests/test_store.py
tests/test_table.py
tests/test_trap.py
wasmtime/_instance.py

Update for `Store` changes in wasmtime

Update to latest wasmtime API

---

tests/test_wasi.py
wasmtime/_wasi.py

* Document them
* Read the return value and raise an exception if it fails
Closes #31

Update wasi `*_file` accessors

---

wasmtime/_bindings.py
wasmtime/_config.py

Sync with latest header file as well.

Add new config method

---

setup.py

Add a py.typed file for mypy

---

bindgen.py
tests/test_config.py
tests/test_memory.py
wasmtime/_bindings.py
wasmtime/_config.py
wasmtime/_memory.py
wasmtime/_types.py

Mostly just a few new types/limits here and there, not much of a change.

Add support for the memory64 proposal

---

download-wasmtime.py
tests/test_trap.py
wasmtime/__init__.py
wasmtime/_bindings.py
wasmtime/_error.py
wasmtime/_ffi.py
wasmtime/_trap.py

This migrates to the `dev` tag temporarily to work with the recent trap changes.

Update for latest trap changes in upstream

---

wasmtime/_config.py
wasmtime/_engine.py
wasmtime/_store.py

Add some more type annotations and correct a few others.

Fix some new issues pointed out by mypy

---

.github/actions/setup/action.yml
ci/download-wasmtime.py
rust/Cargo.lock
rust/Cargo.toml
rust/bindgen.wit
rust/bindgen/Cargo.toml
rust/bindgen/src/bindgen.rs
rust/bindgen/src/imports.rs
rust/bindgen/src/lib.rs
rust/bindgen/src/source.rs
rust/python.wit
rust/wasi_snapshot_preview1/src/lib.rs
tests/codegen/test_records.py
tests/codegen/test_variants.py
wasmtime/_error.py

This pulls in support for `use` and works with more recently generated components.

Update WIT bindgen tooling

---

.github/workflows/main.yml

Fix #146 
Can you please release the lib after merging this?

fix: macOS arm64 now correctly build generated folder

---

rust/bindgen/src/bindgen.rs
tests/codegen/test_variants.py

While developing and testing `componentize-py`, I've sought to mimic `wasmtime-py`'s type binding generator.  In doing so, I noticed that certain types were ambiguous, e.g.:
```python
Option[Option[int]] # None is ambiguous
Foo = Union[int, float] # OK
Bar = Union[Foo, int, float] # e.g. 42 and 0.42 are ambiguous
Baz = Union[Optional[int], int] # e.g. 42 is ambiguous
```
This fixes the above cases by:
- Introducing a `Some` type for use with nested `option` types
- Disallowing nested raw `union`s and `option`s inside raw `union`s

avoid ambiguous generated types

---

README.md

Fix component example in README

---

tests/test_trap.py
wasmtime/_error.py

Fix stringifying an exit trap

---

ci/download-wasmtime.py
rust/bindgen/src/bindgen.rs
wasmtime/_ffi.py
wasmtime/_module.py
wasmtime/loader.py

This makes the code a bit shorter and more idiomatic.

MAINT Use pathlib instead of os.path

---

wasmtime/_module.py

FIX Python 3.7, 3.8 Union support

---

.github/workflows/main.yml

Mimicking bytecodealliance/wasmtime#8800 over here.

Try migrating actions to deploy to gh-pages

---

ci/download-wasmtime.py
rust/Cargo.lock
rust/Cargo.toml
rust/src/bindgen.rs
setup.py

Bump to 22.0.0

---

ci/download-wasmtime.py
rust/Cargo.lock
rust/Cargo.toml
rust/src/bindgen.rs
setup.py

Also bump the package version to 25.0.0

Update to Wasmtime 25.0.0

---

.github/workflows/main.yml
README.md
setup.py
tests/bindgen/__init__.py

Skip componentize-py tests on older Python

---

.github/workflows/main.yml

Looks like PyPI doesn't like it

Remove MinGW wheel
